apiVersion: apps/v1
kind: Deployment
metadata:
  name: oke-sample
  labels:
    app: oke-sample
spec:
  selector:
    matchLabels:
      app: oke-sample

  template:
    metadata:
      labels:
        app: oke-sample
    spec:
      containers:
      - name: oke-sample
        image: shiftyou/oke-sample
        env:
        - name: MYSQL_SERVICE_HOST
          value: oke-mysql.default
        ports:
        - containerPort: 8080
          name: oke-sample
---
apiVersion: v1
kind: Service
metadata:
  name: oke-sample
  labels:
    app: oke-sample
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: oke-sample
  type: LoadBalancer